import 'dart:convert';

import 'package:syncer/syncer.dart';

class IsarSyncerMergeException implements Exception {
  final String message;
  const IsarSyncerMergeException(this.message);
  @override
  String toString() => 'opto-sync Isar: $message';
}

/// Reconciles JSON-compatible Isar embedded/object fields in memory.
///
/// Call [mergeMaps] and put the owning object inside one `isar.writeTxn`.
class IsarSyncer {
  final Syncer syncer;
  final MergeOptions options;

  IsarSyncer(this.syncer, {MergeOptions? options})
      : options = options ??
            MergeOptions(
              arrayStrategy: ArrayMergeStrategy.mergeByKey,
              resolveByTimestamp: true,
              lwwKeys: 'updatedAt,syncedAt',
            );

  Map<String, dynamic> mergeMaps(
    Map<String, dynamic> stored,
    Map<String, dynamic> incoming,
  ) {
    final merged = syncer.tryMerge(
      jsonEncode(stored),
      jsonEncode(incoming),
      options: options,
    );
    if (merged == null) {
      throw const IsarSyncerMergeException('native merge failed');
    }
    final decoded = jsonDecode(merged);
    if (decoded is! Map<String, dynamic>) {
      throw const IsarSyncerMergeException('merged value is not an object');
    }
    return decoded;
  }

  /// Closure form for collection-specific code generated by Isar.
  Future<Map<String, dynamic>> reconcile({
    required Future<Map<String, dynamic>?> Function() load,
    required Future<void> Function(Map<String, dynamic>) save,
    required Map<String, dynamic> incoming,
  }) async {
    final merged = mergeMaps(await load() ?? <String, dynamic>{}, incoming);
    await save(merged);
    return merged;
  }
}
